[file:mesh_seuk_MG.nc]
mode=auto
source=$MESH_DIR/mesh_seuk_MG.nc

[namelist:base_mesh]
!!f_lat_deg=
file_prefix='mesh_seuk_MG'
!!fplane=
topology='non_periodic'

[namelist:files]
aerosols_ancil_path='aerosol_clims/glomap/qrclim.aerosols_L70_O70.ugrid'
ancil_directory='$DATADIR/ral4b1/seuk/ancils'
hydtop_ancil_path='hydrol_lsh/hydrosheds/qrparm.hydtop.ugrid'
land_area_ancil_path='land_sea_mask/cci/qrparm.mask.ugrid'
lbc_directory='$DATADIR/ral4b1/seuk'
lbc_filename='alabc_lfric'
orography_mean_ancil_path='orography/SRTM_3arc/v3/qrparm.orog_merged.ugrid'
orography_subgrid_ancil_path='orography/SRTM_3arc/v3/qrparm.orog_merged.ugrid'
ozone_ancil_path='ozone/sparc/1994-2005/qrclim.ozone_L70_O70.ugrid'
plant_func_ancil_path='vegetation/func_type_modis/qrparm.veg.func.ugrid'
sea_ancil_path='general_sea/GlobColour/qrclim.sea.ugrid'
sea_ice_ancil_path='sstice/hadisst_6190/qrclim.seaice.ugrid'
soil_ancil_path='soil_parameters/hwsd_vg/qrparm.soil.ugrid'
sst_ancil_path='sstice/hadisst_6190/qrclim.sst.ugrid'
start_dump_directory='$DATADIR/ral4b1/seuk'
start_dump_filename='astart_lfric'
surface_frac_ancil_path='vegetation/fractions_cci/qrparm.veg.frac.ugrid'

[namelist:initialization]
lbc_option='um2lfric_file'

[namelist:partitioning]
partitioner='planar'

[namelist:time]
calendar_origin='2021-07-29 00:00:00'
calendar_start='2021-07-29 00:00:00'
